config/routes.rb
EKbri::Application.routes.draw do

  resources :visas, controller: 'immigration/visa'
  resources :visafamilys, controller: 'immigration/visafamily'
  resources :visagroups, controller: 'immigration/visagroup'
  resources :passports, controller: 'immigration/passport'
  resources :reports, controller: 'immigration/report'  
  resources :cases
    
  get "dashboard/protocols", :to => "protocol#index"
  
  authenticated :user do
    root to: 'welcome#index', as: :authenticated_root
  end

  unauthenticated do
    root to: "welcome#index"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  devise_scope :user do 
    get "/users/sign_out" => "devise/sessions#destroy" 
  end 
  
  resources :users
  get "searchuser", :to => "users#search"
  
  get "infovisas", :to => "immigration/visa#info"   
  get "infopassports", :to => "immigration/passport#info"
  get "inforeports", :to => "immigration/report#info"
  get "bantuan", :to => "cases#info"
  get "lapormasalah", :to => "cases#index"
  get "marriage/info", :to => "immigration/marriage#info"
  
  get "overview", :to => "immigration/flow#systemoverview"
  get "payment", :to => "immigration/flow#systempayment"
  get "visaflow", :to => "immigration/flow#visa"   
  get "visadocs", :to => "immigration/flow#visadocs"
  get "passportflow", :to => "immigration/flow#passport"
  get "passportdocs", :to => "immigration/flow#passportdocs"
  get "reportflow", :to => "immigration/flow#report"
  get "reportdocs", :to => "immigration/flow#reportdocs"

  get "finishgroupapply", :to => "immigration/visa#finishing_application"
  get "visas/reapply/:id", :to => "immigration/visa#reapply"
  get "passports/reapply/:id", :to => "immigration/passport#reapply"
  
  get "dashboard/index"
  get "dashboard/masalahwni", :to => "cases#masalahwni"
  get "dashboard/formulirmasalahwni", :to => "cases#formulirmasalahwni", as: "formulirmasalahwni"
  match "dashboard/deletemasalahwni/:id", to: "cases#destroy", as: "deletemasalahwni", via: :get

  get "dashboard/counsel"
  get "dashboard/immigration"
  get "dashboard/immigration/:document" => "dashboard#immigration" 
  get "dashboard/employment_indonesia"
  get "dashboard/employment_korea"
  get "dashboard/tabulation"
  get "dashboard/statistics"
  get "dashboard", :to => "dashboard#index"
  
  get "welcome/concept"
  get "concept/index"
  get "concept", :to => "concept#index"
  
  match "statistics", :to => "statistics#index", via: :get
  
  get "visa/show/all", :to => "desktop#show_all_sisari"
  get "lapordiri/show/all", :to => "desktop#show_all_lapordiri"
  get "lapordiri/show/history/:user_id", :to => "desktop#show_all_lapordiri_history"
  get "passport/show/all", :to => "desktop#show_all_spri"
  get "case/list/all", :to => "desktop#show_all_cases"
  get "dashboard/service/:document", :to => "dashboard#immigration"
  get "admin/service/:document/:id", :to => "dashboard#immigration"
  get "dashboard/syncpanel", :to => "dashboard#syncpanel"
  get "journal/list/all", :to => "journal#show_all_journal"

  
  
  match "passport/tospri/:id", to: "desktop#exec_toSPRI", via: :post
  match "visa/tosisari/:id", to: "desktop#exec_toSisari", via: :post
  
  get "passports/:id/check", :to => "immigration/passport#check"
  get "visas/:id/check", :to => "immigration/visa#check"
  get "reports/:id/check", :to => "immigration/report#check"
  get "reports/:whosign/:id", :to => "immigration/report#show"
  get "reports/user/print/:id", :to => "immigration/report#show"
  
  get "protocol/synccloudtolocal/:collection", :to => "protocol#syncCollectionCloudtoLocal"
  get "protocol/syncdbcomplete", :to => "protocol#syncDBComplete"
  

  match "report/findbynameandbirth", to: "immigration/report#findbyNameandBirth", via: :get
  
  get "report/panel/periodical", :to => "dashboard#periodical_reporting"
  get "report/panel/periodical_printed_based", :to => "dashboard#periodical_reporting_printed_based"
  match "report/generate/periodical", to: "dashboard#generate_periodical_reporting", via: :post  
  match "report/generate/periodical_printed_based", to: "dashboard#generate_periodical_reporting_printed_based", via: :post
  
  get "export/table/:doc", :to => "desktop#export_table"
  
  get '/images/:name', :to => 'images#show', :as => :custom_image
  
  get "finishgroupapply", :to => "immigration/visa#finishing_application"
  get "deletepassportviadashboard/:id", :to => "desktop#destroy_passport", via: :delete, :as => :deletepassportviadashboard
  get "deletevisaviadashboard/:id", :to => "desktop#destroy_visa", via: :delete, :as => :deletevisaviadashboard
  get "deleteuserviadashboard/:id", :to => "desktop#destroy_user", via: :delete, :as => :deleteuserviadashboard
  
  get "visas/reapply/:id", :to => "immigration/visa#reapply"
  get "passports/reapply/:id", :to => "immigration/passport#reapply"
  
  get "dashboard/reference/list", :to => "reference#index"
  get "dashboard/reference/edit/:type/:id", :to => "reference#edit"
  match "/dashboard/reference/update_visafee", :to => "reference#update_visafee", via: :put, :as => :update_visafee_list
  match "/dashboard/reference/update_passportfee", :to => "reference#update_passportfee", via: :put, :as => :update_passportfee_list
  match "/dashboard/reference/update_signature", :to => "reference#update_reference", via: :put, :as => :update_reference_list
  
  get "passport/payment/:id", :to => "immigration/passport#payment"
  match "passport/payment/:id", to: "immigration/passport#update_payment", via: :patch, :as => :payment_proceed
  
  get "visas/compile/:ref_id", :to => "immigration/visa#show_receipt", :as => :visa_compile
  get "visas/payment/:ref_id", :to => "immigration/visa#payment"
  match "visas/payment/:ref_id", to: "immigration/visa#update_payment", via: :patch, :as => :visa_payment_proceed

  match "report/admin/:id/edit", to: "immigration/report#adminupdate", via: :patch, :as => :adminreportedit
  get "journal/show/:id", :to => "journal#retrieve_document_journal", :as => :document_journal
  get "samplepayment", :to =>"welcome#showsamplebayar"
  
  get "visas/group/:ref_id", to: "immigration/visa#group_recap"
  
  get "delete/user/passport/:id", :to => "immigration/passport#destroy", :as => :userdeletepassport
  get "delete/user/visa/:id", :to => "immigration/visa#destroy", :as => :userdeletevisa
  
  get "playground", :to => "playground#index"
  match "experiment", :to => "playground#experiment", via: :all
  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!#if user_signed_in?, current_user.full_name, etc. 
  before_filter :check_access
  #because /layouts/dashboard.html.erb exists, default layout used is "dashboard"
  
  def index
    @allvisa = Visa.all.count
    @allpassport = Passport.all.count
    @allreport = Report.all.count
  end
  
  def counsel
  
  end
  
  def immigration
    if params[:document] == "visa" then

      @document = "dashboard/service_visa"
      
    elsif params[:document] == "passport"
      @document = "dashboard/service_passport"
      
    elsif params[:document] == "prep_spri" then
      
      vipacounter = 3000      
      
      @document = "dashboard/tospri_prep"
      @passport = Passport.find(params[:id])
      
    elsif params[:document] == "prep_visa" then
      
      @document = "dashboard/tosisari_prep"
      @visa = Visa.find(params[:id])    
       
    elsif params[:document] == "lapordiri" then
      
      @document = "dashboard/service_report"
      
    elsif params[:document] == "journal"
      
      @document = "dashboard/service_journal"
      
    elsif params[:document] == "masalahwni"
      
      @document = "dashboard/service_case"
      
    else  

    
    end
  end
  
  def tabulation
  
  end
  
  def employment_indonesia
  
  end
  
  def employment_korea
    
  end
  
  def statistics
    @document = "dashboard/statistics"
    #@redis_sample = $redis.get('ali')
  end 
  

  def syncpanel
    
    @syncdata = current_user.sync
    
    @document = "dashboard/syncpanel"
    render 'immigration'
  end 
  
  
  def periodical_reporting
    @layout_part = 'top'
  end
  
  def periodical_reporting_printed_based
    @layout_part = 'top'
  end    
  
  def generate_periodical_reporting
    @layout_part = 'bottom'
    periodical_post_params()
    
    if(params[:periodical][:startperiod].present? && params[:periodical][:endperiod].present?)
      
      
      @daterange = { 'startperiod' => params[:periodical][:startperiod], 'endperiod' => params[:periodical][:endperiod] }
      
      @visa = Visa.where(:payment_date => {'$gte' => params[:periodical][:startperiod],'$lte' => params[:periodical][:endperiod]})
      @passport = Passport.where(:payment_date => {'$gte' => params[:periodical][:startperiod],'$lte' => params[:periodical][:endperiod]})
            
      @passportfee = Passportfee.all
      @visafee = Visafee.all
      
      if(params[:type]=='rekap')
        respond_to do |format|
          format.pdf do
            render :pdf         => "Rekapitulasi Bukti Visa & Paspor " + params[:periodical][:startperiod] + " _ " + params[:periodical][:endperiod] + " (Payment Date Based)",
                   :disposition => "attachment",
                   :template    => 'dashboard/report/pdfs.html.erb',
                   :page_size   => 'A4'                          
                   
          end
        end
        
      else
        respond_to do |format|
          format.pdf do
            render :pdf         => "Rekapitulasi Visa & Paspor " + params[:periodical][:startperiod] + " _ " + params[:periodical][:endperiod] + " (Payment Date Based)",
                   :disposition => "attacment",
                   :template    => 'dashboard/report/rekap.html.erb',
                   :page_size   => 'A4',                           
                   :footer      => { :center => "The Embassy of Republic of Indonesia at Seoul" }
          end
        end
        
      end      
        
    else     
       
       redirect_to :back, :flash => { warning: "Laporan Gagal Dibuat" }
          
    end    
  end
  
  def generate_periodical_reporting_printed_based
    @layout_part = 'bottom'
    periodical_post_params()
    
    if(params[:periodical][:startperiod].present? && params[:periodical][:endperiod].present?)
      
      
      @daterange = { 'startperiod' => params[:periodical][:startperiod], 'endperiod' => params[:periodical][:endperiod] }
      
      @visa = Visa.where(:printed_date => {'$gte' => params[:periodical][:startperiod],'$lte' => params[:periodical][:endperiod]})
      @passport = Passport.where(:printed_date => {'$gte' => params[:periodical][:startperiod],'$lte' => params[:periodical][:endperiod]})
            
      @passportfee = Passportfee.all
      @visafee = Visafee.all
      
      if(params[:type]=='rekap')
        respond_to do |format|
          format.pdf do
            render :pdf         => "Rekapitulasi Bukti Visa & Paspor " + params[:periodical][:startperiod] + " _ " + params[:periodical][:endperiod] + " (Printed Date Based)",
                   :disposition => "attachment",
                   :template    => 'dashboard/report/pdfs.html.erb',
                   :page_size   => 'A4'                          
                   
          end
        end
        
      else
        respond_to do |format|
          format.pdf do
            render :pdf         => "Rekapitulasi Visa & Paspor " + params[:periodical][:startperiod] + " _ " + params[:periodical][:endperiod]  + " (Printed Date Based)",
                   :disposition => "attacment",
                   :template    => 'dashboard/report/rekap.html.erb',
                   :page_size   => 'A4',                           
                   :footer      => { :center => "The Embassy of Republic of Indonesia at Seoul" }
          end
        end
        
      end      
        
    else     
       
       redirect_to :back, :flash => { warning: "Laporan Gagal Dibuat" }
          
    end    
  end
  
  protected
  def group_passportfee_type
      
  end
  

  def check_access
    if !current_user.has_role? :admin then
      redirect_to root_path, :flash => { :warning => "The URL you attempt to access is not exist." }
    else  
    end
  end

  
  def periodical_post_params
    params.require(:periodical).permit(:startperiod, :endperiod, :type)
  end
  
  
  private
  def redis
    @redis ||= Redis.new
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def dashboard_immigration(document)
    "/dashboard/immigration/#{document}"
  end
end

app/views/dashboard/_breadcrumb.html.erb
<ol class="breadcrumb">
	<li>
		<i class="clip-home-2"></i>
		&nbsp;
		<%= link_to "E-KBRI", authenticated_root_path %>
	</li>
	<li class="active">
		<% if action_name == "index" then %>
			<%= "Dashboard" %>
		<% elsif action_name == "counsel" %>
			<%= "Konsuler" %>
		<% elsif action_name == "immigration" %>
			<%= "Imigrasi" %>
		<% elsif action_name == "employment_indonesia" %>
			<%= "BNP2TKI" %>
		<% elsif action_name == "employment_korea" %>
			<%= "HRD Korea" %>
		<% else %>
			<%= action_name.titleize %>
		<% end %>
	</li>
	<!--<li class="search-box">
		<form class="sidebar-search">
			<div class="form-group">
				<input type="text" placeholder="Cari (Kata Kunci?)">
				<button class="submit">
					<i class="clip-search-3"></i>
				</button>
			</div>
		</form>
	</li>-->
</ol>

app/views/dashboard/_message.html.erb
<li class="dropdown">
	<a class="dropdown-toggle" data-close-others="true" data-hover="dropdown" data-toggle="dropdown" href="index.html#">
		<i class="clip-bubble-3"></i><span class="badge"> 4</span>
	</a>
	<ul class="dropdown-menu posts">
		<li>
			<span class="dropdown-menu-title"> Anda memiliki 4 pesan baru</span>
		</li>
		<li>
		<div class="drop-down-wrapper">
			<ul>
											<li>
												<a href="javascript:;">
													<div class="clearfix">
														<div class="thread-image">
															<%= image_tag("/assets/images/dashboard/avatar-2.jpg") %>
														</div>
														<div class="thread-content">
															<span class="author">Damayanti</span>
															<span class="preview">Pak Didik, Dubes mengagendakan rapat Rabu, 18
															 Desember 2013.</span>
															<span class="time"> Just Now</span>
														</div>
													</div>
												</a>
											</li>
											<li>
												<a href="javascript:;">
													<div class="clearfix">
														<div class="thread-image">
															<%= image_tag("/assets/images/dashboard/avatar-4.jpg") %>
														</div>
														<div class="thread-content">
															<span class="author">Da Hyeon</span>
															<span class="preview">Pak, 
															fungsi konsuler dan politik diagendakan bertemu imigrasi korea minggu 
															depan, 19 Desember 2013 di COEX.
															</span>
															<span class="time">2 mins</span>
														</div>
													</div>
												</a>
											</li>
											<li>
												<a href="javascript:;">
													<div class="clearfix">
														<div class="thread-image">
															<%= image_tag("/assets/images/dashboard/avatar-3.jpg") %>
														</div>
														<div class="thread-content">
															<span class="author">Deni Sugandi</span>
															<span class="preview">Jadwal protokoler kedatangan BPK kapan ya Pak?
															</span>
															<span class="time">8 hrs</span>
														</div>
													</div>
												</a>
											</li>
											<li>
												<a href="javascript:;">
													<div class="clearfix">
														<div class="thread-image">
															<%= image_tag("/assets/images/dashboard/avatar-5.jpg") %>
														</div>
														<div class="thread-content">
															<span class="author">John A. Prasetio</span>
															<span class="preview">Pak Didik, rapat tanggal 20 Desember 2013 dengan
															 Kemenlu Korea. Tolong dampingi saya.
															 </span>
															<span class="time">14 hrs</span>
														</div>
													</div>
												</a>
											</li>
			</ul>
		</div>
		</li>
		<li class="view-all">
			<a href="pages_messages.html">
				Lihat semua pesan. <i class="fa fa-arrow-circle-right"></i>
			</a>
		</li>
	</ul>
</li>

app/views/dashboard/_notification.html.erb
<li class="dropdown">
	<a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" data-close-others="true" href="index.html#">
		<i class="clip-list"></i><span class="badge"> 10</span>
	</a>
	<ul class="dropdown-menu notifications">
		<li>
			<span class="dropdown-menu-title"> Anda memiliki 10 Notifikasi</span>
		</li>
		<li>
			<div class="drop-down-wrapper">
				<ul>
					<li>
												<a href="javascript:void(0)">
													<span class="label label-success">Imigrasi</span>
													<span class="message"> Permohonan Visa</span>
													<span class="label label-danger time" style="opacity: 1;"> 50</span>
												</a>
					</li>
					<li>
												<a href="javascript:void(0)">
													<span class="label label-info">Konsuler</span>
													<span class="message"> Permohonan Surat Nikah</span>
													<span class="label label-warning time" style="opacity: 1;"> 20</span>
												</a>
					</li>
					<li>
												<a href="javascript:void(0)">
													<span class="label label-warning">Ketenagakerjaan</span>
													<span class="message"> Pendataan TKI</span>
													<span class="label label-danger time"> 140</span>
												</a>
					</li>
					<li>
												<a href="javascript:void(0)">
													<span class="label label-success">Imigrasi</span>
													<span class="message"> Permohonan Paspor</span>
													<span class="label label-danger time" style="opacity: 1;"> 70</span>
												</a>
					</li>
					<li>
												<a href="javascript:void(0)">
													<span class="label label-success">Imigrasi</span>
													<span class="message"> Permohonan Visa</span>
													<span class="label label-danger time" style="opacity: 1;"> 50</span>
												</a>
					</li>
					<li>
												<a href="javascript:void(0)">
													<span class="label label-info">Konsuler</span>
													<span class="message"> Permohonan Surat Nikah</span>
													<span class="label label-warning time" style="opacity: 1;"> 20</span>
												</a>
					</li>
					<li>
													<a href="javascript:void(0)">
													<span class="label label-warning">Ketenagakerjaan</span>
													<span class="message"> Pendataan TKI</span>
													<span class="label label-danger time"> 140</span>
												</a>
					</li>
					<li>
												<a href="javascript:void(0)">
													<span class="label label-success">Imigrasi</span>
													<span class="message"> Permohonan Paspor</span>
													<span class="label label-danger time" style="opacity: 1;"> 70</span>
												</a>
					</li>
					<li>
												<a href="javascript:void(0)">
													<span class="label label-info">Konsuler</span>
													<span class="message"> Permohonan Surat Lahir</span>
													<span class="label label-warning time" style="opacity: 1;"> 17</span>
												</a>
					</li>
					<li>
												<a href="javascript:void(0)">
													<span class="label label-info">Konsuler</span>
													<span class="message"> Permohonan Legalisasi</span>
													<span class="label label-danger time"> 13</span>
												</a>
											</li>
				</ul>
			</div>
		</li>
		<li class="view-all">
			<a href="javascript:void(0)">
				Lihat seluruh notifikasi. <i class="fa fa-arrow-circle-right"></i>
			</a>
		</li>
	</ul>
</li>

app/views/dashboard/_service_passport.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : name %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
<%= render "dashboard/tabulationpassport" %>

app/views/dashboard/_service_visa.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : name %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
<%= render "dashboard/tabulationvisa" %>

app/views/dashboard/_stylesheet.html.erb
<%= stylesheet_link_tag "/assets/plugins/bootstrap/css/bootstrap.min.css" %>
<%= stylesheet_link_tag "/assets/css/font-awesome.css"%>
<%= stylesheet_link_tag "/assets/fonts/style.css"%>
<%= stylesheet_link_tag "/assets/css/dashboard/main.css"%>
<%= stylesheet_link_tag "/assets/css/dashboard/main-responsive.css"%>
<%= stylesheet_link_tag "/assets/plugins/iCheck/skins/all.css"%>
<%= stylesheet_link_tag "/assets/plugins/bootstrap-colorpalette/css/bootstrap-colorpalette.css"%>
<!--<link rel="stylesheet/less" type="text/css" href="assets/css/dashboard/styles.less">-->
<%= stylesheet_link_tag "/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css"%>
<%= stylesheet_link_tag "/assets/css/dashboard/theme_indonesia.css"%>
<%= stylesheet_link_tag "/assets/plugins/jquery-ui/jquery-ui-1.10.4.custom.min.css"%>
<!--[if IE 7]>
<link rel="stylesheet" href="assets/plugins/font-awesome/css/font-awesome-ie7.min.css">
<![endif]-->
<%= stylesheet_link_tag "/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css"%>
<link rel="shortcut icon" href="/assets/favicon.ico" />

app/views/dashboard/_tabulationcase.html.erb
<div class="row">
	<div class="col-md-12">
							<!-- start: TABLE WITH IMAGES PANEL -->
							<div class="panel panel-default">
								<div class="panel-heading">
									<i class="fa fa-external-link-square"></i>

									WNI Cases Recapitulation
									<div class="panel-tools">
										<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
										</a>										
																													
									</div>
								</div>
								<div class="panel-body">
									<script type="text/javascript">	
										$(document).ready(function(){									
										    $("#sample-table-2").dataTable({
										    	 "bProcessing": true,
										    	 "bSort": false,
										         "bServerSide": true,
										         "iDisplayLength": 100,
										         "sAjaxSource": "/case/list/all",
										         "aoColumns": [
										          null,
											      null,
											      null,
											      null,
											      null,											      
											      { "bSortable": false }											      
											    ]
										    });
										});									
									</script>									
									
									<style>
										#sample-table-2 td {
											text-align:center;
										}
									</style>
										
									<table class="table table-striped table-bordered table-hover" id="sample-table-2">
										<thead>
											<tr>				
																			
												<th class="center" width="170">No. Kasus</th>
												<th class="center" width="250">Nama</th>
												<th class="center" width="250">Status Kasus</th>
												<th class="center" width="250">Waktu & Tanggal Lapor</th>																								
												<th class="center" width="150"></th>												
											</tr>
										</thead>
										<tbody>								
																						

										</tbody>
									</table>
								</div>
							</div>
							<!-- end: TABLE WITH IMAGES PANEL -->
	</div>
</div>

app/views/dashboard/_tabulationjournal.html.erb
<div class="row">
	<div class="col-md-12">
							<!-- start: TABLE WITH IMAGES PANEL -->
							<div class="panel panel-default">
								<div class="panel-heading">
									<i class="fa fa-external-link-square"></i>

									Journal Viewer
									<div class="panel-tools">
										<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
										</a>										
																													
									</div>
								</div>
								<div class="panel-body">
									<script type="text/javascript">	
										$(document).ready(function(){									
										    $("#sample-table-2").dataTable({
										    	 "bProcessing": true,
										    	 "bSort": false,
										         "bServerSide": true,
										         "iDisplayLength": 100,
										         "sAjaxSource": "/journal/list/all",
										         "aoColumns": [
										          null,
											      null,
											      null,
											      null,
											      null,											      
											      { "bSortable": false }											      
											    ]
										    });
										});									
									</script>									
									
									<style>
										#sample-table-2 td {
											text-align:center;
										}
									</style>
										
									<table class="table table-striped table-bordered table-hover" id="sample-table-2">
										<thead>
											<tr>				
																			
												<th class="center" width="170">Action</th>
												<th class="center" width="250">By</th>
												<th class="center" width="250">Method</th>
												<th class="center" width="250">On</th>
												<th class="center" width="250">At</th>																								
												<th class="center" width="150">Reference</th>												
											</tr>
										</thead>
										<tbody>								
																						

										</tbody>
									</table>
								</div>
							</div>
							<!-- end: TABLE WITH IMAGES PANEL -->
	</div>
</div>

app/views/dashboard/_tosisari_prep.html.erb
<h2>Prepare Data for SISARI</h2>
Visa Application Ref. Number : <b><%= @visa.ref_id %></b>
<div style="clear:both;margin-bottom:8px;"></div>
<%= render 'forms/prepare_sisari' %>

app/views/dashboard/_tospri_prep.html.erb
<h2>Prepare Data for SPRI</h2>
Passport Application Ref. Number : <b><%= @passport.ref_id %></b>
<div style="clear:both;margin-bottom:8px;"></div>
<%= render 'forms/prepare_spri' %>

app/views/dashboard/employment_indonesia.html.erb
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
</script>

app/views/dashboard/employment_korea.html.erb
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
</script>