config/routes.rb
EKbri::Application.routes.draw do

  resources :visas, controller: 'immigration/visa'
  resources :visafamilys, controller: 'immigration/visafamily'
  resources :visagroups, controller: 'immigration/visagroup'
  resources :passports, controller: 'immigration/passport'
  resources :reports, controller: 'immigration/report'  
  resources :cases
    
  get "dashboard/protocols", :to => "protocol#index"
  
  authenticated :user do
    root to: 'welcome#index', as: :authenticated_root
  end

  unauthenticated do
    root to: "welcome#index"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  devise_scope :user do 
    get "/users/sign_out" => "devise/sessions#destroy" 
  end 
  
  resources :users
  get "searchuser", :to => "users#search"
  
  get "infovisas", :to => "immigration/visa#info"   
  get "infopassports", :to => "immigration/passport#info"
  get "inforeports", :to => "immigration/report#info"
  get "bantuan", :to => "cases#info"
  get "lapormasalah", :to => "cases#index"
  get "marriage/info", :to => "immigration/marriage#info"
  
  get "overview", :to => "immigration/flow#systemoverview"
  get "payment", :to => "immigration/flow#systempayment"
  get "visaflow", :to => "immigration/flow#visa"   
  get "visadocs", :to => "immigration/flow#visadocs"
  get "passportflow", :to => "immigration/flow#passport"
  get "passportdocs", :to => "immigration/flow#passportdocs"
  get "reportflow", :to => "immigration/flow#report"
  get "reportdocs", :to => "immigration/flow#reportdocs"

  get "finishgroupapply", :to => "immigration/visa#finishing_application"
  get "visas/reapply/:id", :to => "immigration/visa#reapply"
  get "passports/reapply/:id", :to => "immigration/passport#reapply"
  
  get "dashboard/index"
  get "dashboard/masalahwni", :to => "cases#masalahwni"
  get "dashboard/formulirmasalahwni", :to => "cases#formulirmasalahwni", as: "formulirmasalahwni"
  match "dashboard/deletemasalahwni/:id", to: "cases#destroy", as: "deletemasalahwni", via: :get

  get "dashboard/counsel"
  get "dashboard/immigration"
  get "dashboard/immigration/:document" => "dashboard#immigration" 
  get "dashboard/employment_indonesia"
  get "dashboard/employment_korea"
  get "dashboard/tabulation"
  get "dashboard/statistics"
  get "dashboard", :to => "dashboard#index"
  
  get "welcome/concept"
  get "concept/index"
  get "concept", :to => "concept#index"
  
  match "statistics", :to => "statistics#index", via: :get
  
  get "visa/show/all", :to => "desktop#show_all_sisari"
  get "lapordiri/show/all", :to => "desktop#show_all_lapordiri"
  get "lapordiri/show/history/:user_id", :to => "desktop#show_all_lapordiri_history"
  get "passport/show/all", :to => "desktop#show_all_spri"
  get "case/list/all", :to => "desktop#show_all_cases"
  get "dashboard/service/:document", :to => "dashboard#immigration"
  get "admin/service/:document/:id", :to => "dashboard#immigration"
  get "dashboard/syncpanel", :to => "dashboard#syncpanel"
  get "journal/list/all", :to => "journal#show_all_journal"

  
  
  match "passport/tospri/:id", to: "desktop#exec_toSPRI", via: :post
  match "visa/tosisari/:id", to: "desktop#exec_toSisari", via: :post
  
  get "passports/:id/check", :to => "immigration/passport#check"
  get "visas/:id/check", :to => "immigration/visa#check"
  get "reports/:id/check", :to => "immigration/report#check"
  get "reports/:whosign/:id", :to => "immigration/report#show"
  get "reports/user/print/:id", :to => "immigration/report#show"
  
  get "protocol/synccloudtolocal/:collection", :to => "protocol#syncCollectionCloudtoLocal"
  get "protocol/syncdbcomplete", :to => "protocol#syncDBComplete"
  

  match "report/findbynameandbirth", to: "immigration/report#findbyNameandBirth", via: :get
  
  get "report/panel/periodical", :to => "dashboard#periodical_reporting"
  get "report/panel/periodical_printed_based", :to => "dashboard#periodical_reporting_printed_based"
  match "report/generate/periodical", to: "dashboard#generate_periodical_reporting", via: :post  
  match "report/generate/periodical_printed_based", to: "dashboard#generate_periodical_reporting_printed_based", via: :post
  
  get "export/table/:doc", :to => "desktop#export_table"
  
  get '/images/:name', :to => 'images#show', :as => :custom_image
  
  get "finishgroupapply", :to => "immigration/visa#finishing_application"
  get "deletepassportviadashboard/:id", :to => "desktop#destroy_passport", via: :delete, :as => :deletepassportviadashboard
  get "deletevisaviadashboard/:id", :to => "desktop#destroy_visa", via: :delete, :as => :deletevisaviadashboard
  get "deleteuserviadashboard/:id", :to => "desktop#destroy_user", via: :delete, :as => :deleteuserviadashboard
  
  get "visas/reapply/:id", :to => "immigration/visa#reapply"
  get "passports/reapply/:id", :to => "immigration/passport#reapply"
  
  get "dashboard/reference/list", :to => "reference#index"
  get "dashboard/reference/edit/:type/:id", :to => "reference#edit"
  match "/dashboard/reference/update_visafee", :to => "reference#update_visafee", via: :put, :as => :update_visafee_list
  match "/dashboard/reference/update_passportfee", :to => "reference#update_passportfee", via: :put, :as => :update_passportfee_list
  match "/dashboard/reference/update_signature", :to => "reference#update_reference", via: :put, :as => :update_reference_list
  
  get "passport/payment/:id", :to => "immigration/passport#payment"
  match "passport/payment/:id", to: "immigration/passport#update_payment", via: :patch, :as => :payment_proceed
  
  get "visas/compile/:ref_id", :to => "immigration/visa#show_receipt", :as => :visa_compile
  get "visas/payment/:ref_id", :to => "immigration/visa#payment"
  match "visas/payment/:ref_id", to: "immigration/visa#update_payment", via: :patch, :as => :visa_payment_proceed

  match "report/admin/:id/edit", to: "immigration/report#adminupdate", via: :patch, :as => :adminreportedit
  get "journal/show/:id", :to => "journal#retrieve_document_journal", :as => :document_journal
  get "samplepayment", :to =>"welcome#showsamplebayar"
  
  get "visas/group/:ref_id", to: "immigration/visa#group_recap"
  
  get "delete/user/passport/:id", :to => "immigration/passport#destroy", :as => :userdeletepassport
  get "delete/user/visa/:id", :to => "immigration/visa#destroy", :as => :userdeletevisa
  
  get "playground", :to => "playground#index"
  match "experiment", :to => "playground#experiment", via: :all
  

end

app/controllers/immigration/flow_controller.rb
class Immigration::FlowController < ApplicationController
  
  def systemoverview
  end
  
  def systempayment
  end
  
  def visa
  end
  
  def visadocs
  end
  
  def passport
  end
  
  def passportdocs
  end
  
  def report
  end
  
  def reportdocs
  end
  
end

app/controllers/immigration/marriage_controller.rb
class Immigration::MarriageController < ApplicationController
  
  def index
    
  end
  
  def info
    
  end
  
  def create
    
  end
  
  def update
    
  end
  
  def edit
    
  end
  
  def show
    
  end
  
end

app/controllers/immigration/passport_controller.rb
class Immigration::PassportController < ApplicationController
  include SimpleCaptcha::ControllerHelpers

  before_filter :authenticate_user!
  #GET /passport  

  @@VIPACOUNTERDEF = 6600

  
  def index
    #1 Person, 1 Application in 5 years
    #if Passport.where(user_id: current_user).count > 0
    #    redirect_to edit_passport_path(current_user)
    #end
    #We comment this as we want to enable multiple paspors and/or SPLPs
    @passport = Passport.new
  end
  
  def reapply
    redirect_to root_path, :notice => 'You have successfully notified The Embassy staff to recheck your previously incomplete application.'
  end
  
  #GET /new
  def new
  
  end
  

  def check
    @passport = Passport.find(params[:id])    
    render layout: "dashboard"    
  end
  
  def payment
    @passport = Passport.find(params[:id])
  end

  #GET passport/:id
  def show
    @passport = Passport.find(params[:id])
      respond_to do |format|
      format.html { render 'edit' }
      format.json { render json: @passport }
      format.xml { render xml: @passport }
      format.pdf do
          render :pdf            => "Receipt of Passport Application ["+"#{current_user.full_name}"+"]_" + @passport.ref_id,
                 :disposition    => "attachment", #{attachment, inline}                 
                 :template       => "immigration/passport/pasporpayment.html.erb",
                 :layout         => "pdf_layout.html",
                 :encoding       => "utf8"                 
        end

    end
  end
  
  #POST /passport

  def create       
    @passport = [ Passport.new(post_params) ]
    #current_user.passports = @passport    
    tempcache = @passport
    @passport = @passport[0]
    
    if @passport.valid?
      if simple_captcha_valid?
          current_user.passports.push(tempcache)   
          current_user.save
          UserMailer.passport_received_email(@passport).deliver
          current_user.journals.push(Journal.new(:action => 'Created', :model => 'Passport', :method => 'Insert', :agent => request.user_agent, :record_id => @passport.id, :ref_id => @passport.ref_id ))
          flash[:notice] = 'Pengurusan aplikasi paspor anda, berhasil!'
          render 'pasporconfirm.html.erb'
      else        
        @errors = { 'Secret Code' => 'Wrong Code Entered'}
        render 'index'
      end
    else     
      @errors = @passport.errors.messages
      render 'index'
    end    
    

    #debugging
    #logger.debug "We are inspecting PASSPORT PROCESSING PARAMS as follows:"
    #puts params.inspect
    #puts @passport.inspect
  end
  
  #GET /passport/:id/edit
  def edit
    #@passport = Passport.find_by(user_id: params[:id])
    @passport = Passport.find(params[:id])
  end
  
  #PATCH, PUT /passport/:id
  def update
    @passport = Passport.find(params[:id])
    #@passport = Passport.find_by(user_id: params[:id])
    if @passport.update(post_params)
      
      current_user.journals.push(Journal.new(:action => @passport.status, :model => 'Passport', :method => 'Update', :agent => request.user_agent, :record_id => @passport.id, :ref_id => @passport.ref_id ))
      if current_user.has_role? :admin or current_user.has_role? :moderator        
        UserMailer.admin_update_passport_email(@passport).deliver
        redirect_to :back, :notice => 'A Passport Application Data has been updated'
      else
        redirect_to root_path, :notice => 'Anda telah berhasil memperbaharui data pengurusan paspor anda!'
      end     
      
    else
      @errors = @passport.errors.messages
      render 'edit'
    end
  end
  

  def update_payment 
    @passport = Passport.find(params[:id])
    if @passport.update(post_params)    
      current_user.journals.push(Journal.new(:action => @passport.status, :model => 'Passport', :method => 'Update', :agent => request.user_agent, :record_id => @passport.id, :ref_id => @passport.ref_id  ))  
      redirect_to root_path, :notice => 'Data Pembayaran anda berhasil disimpan!'
    else
      @errors = @passport.errors.messages
      render 'payment'
    end
  end
  

  #DELETE /passport/:id
  def destroy 
   @passport = Passport.find(params[:id])
    reference = @passport.ref_id
    if @passport.delete
      current_user.journals.push(Journal.new(:action => 'Removed', :model => 'Passport', :method => 'Delete', :agent => request.user_agent, :record_id => params[:id], :ref_id => reference ))
      redirect_to :back, :notice => "Paspor dengan No. Ref. #{reference} telah berhasil dihapuskan dari sistem."
    else
      redirect_to :back, :notice => "Paspor No. Ref. #{reference} tidak dapat ditemukan."
    end
  end    
  
  private  
    def post_params()
      params.require(:passport).permit(:application_type, :application_reason, :paspor_type, :full_name, :height, :kelamin, :placeBirth, :dateBirth,              
      :citizenship_status, :lastPassportNo, :dateIssued, :placeIssued, :jobStudyInKorea, :jobStudyTypeInKorea, :jobStudyOrganization, :jobStudyAddress, 
      :phoneKorea, :addressKorea, :cityKorea, :phoneIndonesia, :addressIndonesia, :kelurahanIndonesia, :kecamatanIndonesia, :kabupatenIndonesia, :dateArrival, :sendingParty, :photo, :status, :slip_photo, :payment_date, :arc, :dateIssuedEnd, :immigrationOffice, :sponsor_address_prov_kr, :sponsor_address_prov_id, :supporting_doc, :supporting_doc_2, :supporting_doc_3, :supporting_doc_4, :comment, :pickup_office, :pickup_date)

    end
    #Notes: to add attribute/variable after POST params received, do
    #def post_params
    #  params.require(:post).permit(:some_attribute).merge(user_id: current_user.id)
    #end
    def reference_no_passport
      time = Time.new
      coded_date = time.strftime("%y%m%d")
      ref_id = 'D'+coded_date+generate_string(3)
    end
    def generate_string(length=5)
      chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ123456789'
      password = ''
      length.times { |i| password << chars[rand(chars.length)] }
      password = password.upcase
    end
end

app/helpers/immigration/marriage_helper.rb
module Immigration::MarriageHelper
end

app/helpers/immigration/passport_helper.rb
module Immigration::PassportHelper
end

app/helpers/immigration/report_helper.rb
module Immigration::ReportHelper
end

app/helpers/immigration/visa_helper.rb
module Immigration::VisaHelper
end

app/views/immigration/flow/passport.html.erb
<div style="text-align: center; padding-top: 20px; position: relative;">
	<%= image_tag("/assets/images/garuda.png", height: '160', width: '160') %>
	<h1>Welcome to Electronic KBRI Seoul Services (E-KBRI)</h1>
<hr />
	<iframe width="853" height="480" src="https://www.youtube.com/embed/Db7BrVDpZxs?rel=0" frameborder="0" allowfullscreen></iframe>
<hr />
	<div class="row">
		<img src="/images/passport-flow.gif" />
		<h3>PENGUMUMAN PENTING:</h3>
		<p>Paspor anda memiliki nomor baru, silakan segera laporkan ke Imigrasi terdekat perubahan No. Paspor anda dalam waktu 14 hari setelah diterbitkan.
		   Gagal melaporkan No. Paspor baru dalam waktu 14 hari dapat didenda sesuai peraturan Imigrasi Korea Selatan.</p>
	</div>
</div>

app/views/immigration/flow/passportdocs.html.erb
<div class="body" style="padding-top: 20px;">
	<div style="text-align: center;">
		<%= image_tag("/assets/images/garuda.png", height: '160', width: '160') %>
	</div>

	

<body>
	<h1>Persyaratan Pembuatan Paspor</h1>
	<h3>Harap perhatikan persyaratan dokumen untuk masing - masing jenis permohonan paspor. Syarat - syarat dokumen tersebut HARUS di scan/foto dan kemudian diunggah kedalam form aplikasi <i>online</i> </h3>
	<h3>Permohonan Paspor anda <b>tidak akan diproses</b> tanpa syarat - syarat dokumen yang lengkap dan valid</h3>
	<h4><a href="<%= passports_path %>">Klik disini untuk Form Permohonan <i>Online</i></a></h4>
<table border="1" cellpadding="2" cellspacing="1" width="1200" style="font-size:9pt;">
	<thead style="font-weight:bold;text-align:center;background:#CCCCCC;">
		<tr>
			<td colspan="2" rowspan="2">Jenis</td>
			<td rowspan="2">Biaya</td>
			<td colspan="5">Pemegang Paspor</td>
		</tr>
		<tr>
			<td>TKI dan ABK</td>
			<td>Professional</td>
			<td>Ikut Istri/Suami</td>
			<td>Ikut Orang Tua</td>
			<td>Pelajar</td>
		</tr>
	</thead>
	<tr>
		<td rowspan="3" width="100" align="center" style="background:#eeeeee;font-weight:bold;">Paspor 24 Halaman</td>
		<td >Perpanjang Paspor 24 Halaman</td>
		<td style="background:#FFFF99;text-align:center;font-style:italic;">$6.00</td>
		<td>
			<ul>
				<li>Paspor Lama</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Kerja dari Perusahaan</li>
				<li>SLC (Standard Labour Contract)</li>
			</ul>
		</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>		
		<td>Paspor Rusak</td>
		<td style="background:#FFFF99;text-align:center;font-style:italic;">$11.00</td>
		<td>
			<ul>
				<li>Paspor yang Rusak</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Kerja dari Perusahaan</li>
				<li>SLC (Standard Labour Contract)</li>
			</ul>
		</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>		
		<td>Paspor Rusak</td>
		<td style="background:#FFFF99;text-align:center;font-style:italic;">$11.00</td>
		<td>
			<ul>
				<li>Surat Keterangan dari Kepolisian</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Kerja dari Perusahaan</li>
				<li>SLC (Standard Labour Contract)</li>
			</ul>
		</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>		
		<td rowspan="3" align="center" style="background:#eeeeee;font-weight:bold;">Paspor 48 Halaman</td>
		<td>Perpanjang Paspor 48 Halaman</td>
		<td style="background:#FFFF99;text-align:center;font-style:italic;">$22.00</td>
		<td></td>
		<td>
			<ul>
				<li>Paspor Lama</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Kerja dari Perusahaan</li>
				<li>SLC (Standard Labour Contract)</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>Paspor Lama</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Menikah (Buku nikah atau Sertifikat pernikahan)</li>
				<li>Family Registration Card (Kartu Keluarga)</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>Paspor Lama</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Akta Kelahiran</li>
				<li>Surat Keterangan Kerja/Sekolah Orang Tua</li>
				<li>Paspor Orang Tua</li>
				<li>Family Registration Card (Kartu Keluarga)</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>Paspor Lama</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Status Terdaftar dari Universitas di Korea</li>
				<li>Family Registration Card (Kartu Keluarga)</li>
			</ul>
		</td>
		
	</tr>
	
	<tr>		
		
		<td>Paspor Rusak</td>
		<td style="background:#FFFF99;text-align:center;font-style:italic;">$43.00</td>
		<td></td>
		<td>
			<ul>
				<li>Paspor Rusak</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Kerja dari Perusahaan</li>
				<li>SLC (Standard Labour Contract)</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>Paspor Rusak</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Menikah (Buku nikah atau Sertifikat pernikahan)</li>
				<li>Family Registration Card (Kartu Keluarga)</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>Paspor Rusak</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Akta Kelahiran</li>
				<li>Surat Keterangan Kerja/Sekolah Orang Tua</li>
				<li>Paspor Orang Tua</li>
				<li>Family Registration Card (Kartu Keluarga)</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>Paspor Rusak</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Status Terdaftar dari Universitas di Korea</li>
				<li>Family Registration Card (Kartu Keluarga)</li>
			</ul>
		</td>
		
	</tr>
	<tr>		
		
		<td>Paspor Hilang</td>
		<td style="background:#FFFF99;text-align:center;font-style:italic;">$43.00</td>
		<td></td>
		<td>
			<ul>
				<li>Surat Keterangan dari Kepolisian</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Kerja dari Perusahaan</li>
				<li>SLC (Standard Labour Contract)</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>Surat Keterangan dari Kepolisian</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Menikah (Buku nikah atau Sertifikat pernikahan)</li>
				<li>Family Registration Card (Kartu Keluarga)</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>Surat Keterangan dari Kepolisian</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Akta Kelahiran</li>
				<li>Surat Keterangan Kerja/Sekolah Orang Tua</li>
				<li>Paspor Orang Tua</li>
				<li>Family Registration Card (Kartu Keluarga)</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>Surat Keterangan dari Kepolisian</li>
				<li>ARC (Alien Registration Card)</li>
				<li>Pas Foto</li>
				<li>Surat Keterangan Status Terdaftar dari Universitas di Korea</li>
				<li>Family Registration Card (Kartu Keluarga)</li>
			</ul>
		</td>
		
	</tr>
	
</table>

app/views/immigration/flow/report.html.erb
<div style="text-align: center; padding-top: 20px; position: relative;">
	<%= image_tag("/assets/images/garuda.png", height: '160', width: '160') %>
	<h1>Welcome to Electronic KBRI Seoul services (E-KBRI)</h1>
<hr />
	<div class="row">
		<img src="/images/report-flow.gif" />
	</div>
</div>

app/views/immigration/flow/reportdocs.html.erb
<div class="body" style="padding-top: 20px;">
	<div style="text-align: center;">
		<%= image_tag("/assets/images/garuda.png", height: '160', width: '160') %>
	</div>
	<div>
		<h2>LAPORAN KEDATANGAN</h2>
		<p>Bagi warga negara Indonesia yang datang ke Korea Selatan, diharapkan agar melaporkan diri ke KBRI. 
		   Karena, apabila terjadi sesuatu hal, pihak KBRI dapat segera memberikan bantuan yang diperlukan.
		   Cara melaporkan diri anda kini sangat mudah karena bisa melalui sistem pelayanan elektronik KBRI.</p>
		<p>Untuk mengisi formulir, persiapkan dokumen-dokumen berikut ini dalam versi scan/photo yang <b>TERANG/JELAS/TIDAK KABUR </b>:</p>
		<p>1. <b>Paspor Halaman 1 (pertama) dan 2 (kedua)</b> digabung dengan <b>halaman yang terdapat stempel Visa atau stempel kedatangan</b> dari Imigrasi Korea.</p>
		<p>2. <b>Pas foto</b> digital anda. Dianjurkan berlatar belakang putih (lebih disukai) atau merah/biru.</p>
		<p>3. <b>Kartu identitas diri (Alien Card/ID Card)</b> yang dikeluarkan pihak imigrasi Korea.</p>
		<p>Selanjutnya, silahkan klik link formulir <span style="font-size: large;"> <%= link_to 'Pembuatan Lapor Diri', reports_path %></span>.</p>
	</div>
</div>

app/views/immigration/flow/systemoverview.html.erb
<div style="text-align: center; padding-top: 20px; position: relative;">
	<%= image_tag("/assets/images/garuda.png", height: '160', width: '160') %>
	<h1>Welcome to Electronic KBRI Seoul Services (E-KBRI)</h1>
<hr />
	<div class="row">
		<h2>PETUNJUK DALAM BAHASA INDONESIA</h2>
		<img src="/images/ekbri-flow_id.gif" />
	</div>
	<div class="row">
		<h2>GUIDANCE IN ENGLISH</h2>
		<img src="/images/ekbri-flow_en.gif" />
	</div>
</div>

app/views/immigration/flow/systempayment.html.erb
<div style="text-align: center; padding-top: 20px; position: relative;">
	<%= image_tag("/assets/images/garuda.png", height: '160', width: '160') %>
	<h1>Welcome to Electronic KBRI Seoul Services (E-KBRI)</h1>
<hr />
	<div class="row">
		<h2>FEE PAYMENT GUIDANCE IN ENGLISH</h2>
		<p>Please make your payment through KEB Bank (외환은행)'s <b>Indonesian Embassy in Seoul account 650-005012-179</b> & 
			proceed with Dollar currency payment (Foreign Currency Deposit Slip / 외화예금전표 ). 
			Currency : USD. Please rewrite the Reference Number to the Depositor Name section in the payment slip.</p>
		<img src="/images/ekbri-payment-flow_en.gif" />
	</div>
	<div class="row">
		<h2>SAMPLE OF PAYMENT SLIP KEB (외환은행)</h2>
		<img src="/images/sample_form.jpg" />
	</div>
</div>

app/views/immigration/flow/visa.html.erb
<div style="text-align: center; padding-top: 20px; position: relative;">
	<%= image_tag("/assets/images/garuda.png", height: '160', width: '160') %>
	<h1>Welcome to Electronic KBRI Seoul Services (E-KBRI)</h1>
<hr />
	<div class="row">
		<img src="/images/visa-flow.gif" />
	</div>
</div>