config/routes.rb
EKbri::Application.routes.draw do

  resources :visas, controller: 'immigration/visa'
  resources :visafamilys, controller: 'immigration/visafamily'
  resources :visagroups, controller: 'immigration/visagroup'
  resources :passports, controller: 'immigration/passport'
  resources :reports, controller: 'immigration/report'  
  resources :cases
    
  get "dashboard/protocols", :to => "protocol#index"
  
  authenticated :user do
    root to: 'welcome#index', as: :authenticated_root
  end

  unauthenticated do
    root to: "welcome#index"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  devise_scope :user do 
    get "/users/sign_out" => "devise/sessions#destroy" 
  end 
  
  resources :users
  get "searchuser", :to => "users#search"
  
  get "infovisas", :to => "immigration/visa#info"   
  get "infopassports", :to => "immigration/passport#info"
  get "inforeports", :to => "immigration/report#info"
  get "bantuan", :to => "cases#info"
  get "lapormasalah", :to => "cases#index"
  get "marriage/info", :to => "immigration/marriage#info"
  
  get "overview", :to => "immigration/flow#systemoverview"
  get "payment", :to => "immigration/flow#systempayment"
  get "visaflow", :to => "immigration/flow#visa"   
  get "visadocs", :to => "immigration/flow#visadocs"
  get "passportflow", :to => "immigration/flow#passport"
  get "passportdocs", :to => "immigration/flow#passportdocs"
  get "reportflow", :to => "immigration/flow#report"
  get "reportdocs", :to => "immigration/flow#reportdocs"

  get "finishgroupapply", :to => "immigration/visa#finishing_application"
  get "visas/reapply/:id", :to => "immigration/visa#reapply"
  get "passports/reapply/:id", :to => "immigration/passport#reapply"
  
  get "dashboard/index"
  get "dashboard/masalahwni", :to => "cases#masalahwni"
  get "dashboard/formulirmasalahwni", :to => "cases#formulirmasalahwni", as: "formulirmasalahwni"
  match "dashboard/deletemasalahwni/:id", to: "cases#destroy", as: "deletemasalahwni", via: :get

  get "dashboard/counsel"
  get "dashboard/immigration"
  get "dashboard/immigration/:document" => "dashboard#immigration" 
  get "dashboard/employment_indonesia"
  get "dashboard/employment_korea"
  get "dashboard/tabulation"
  get "dashboard/statistics"
  get "dashboard", :to => "dashboard#index"
  
  get "welcome/concept"
  get "concept/index"
  get "concept", :to => "concept#index"
  
  match "statistics", :to => "statistics#index", via: :get
  
  get "visa/show/all", :to => "desktop#show_all_sisari"
  get "lapordiri/show/all", :to => "desktop#show_all_lapordiri"
  get "lapordiri/show/history/:user_id", :to => "desktop#show_all_lapordiri_history"
  get "passport/show/all", :to => "desktop#show_all_spri"
  get "case/list/all", :to => "desktop#show_all_cases"
  get "dashboard/service/:document", :to => "dashboard#immigration"
  get "admin/service/:document/:id", :to => "dashboard#immigration"
  get "dashboard/syncpanel", :to => "dashboard#syncpanel"
  get "journal/list/all", :to => "journal#show_all_journal"

  
  
  match "passport/tospri/:id", to: "desktop#exec_toSPRI", via: :post
  match "visa/tosisari/:id", to: "desktop#exec_toSisari", via: :post
  
  get "passports/:id/check", :to => "immigration/passport#check"
  get "visas/:id/check", :to => "immigration/visa#check"
  get "reports/:id/check", :to => "immigration/report#check"
  get "reports/:whosign/:id", :to => "immigration/report#show"
  get "reports/user/print/:id", :to => "immigration/report#show"
  
  get "protocol/synccloudtolocal/:collection", :to => "protocol#syncCollectionCloudtoLocal"
  get "protocol/syncdbcomplete", :to => "protocol#syncDBComplete"
  

  match "report/findbynameandbirth", to: "immigration/report#findbyNameandBirth", via: :get
  
  get "report/panel/periodical", :to => "dashboard#periodical_reporting"
  get "report/panel/periodical_printed_based", :to => "dashboard#periodical_reporting_printed_based"
  match "report/generate/periodical", to: "dashboard#generate_periodical_reporting", via: :post  
  match "report/generate/periodical_printed_based", to: "dashboard#generate_periodical_reporting_printed_based", via: :post
  
  get "export/table/:doc", :to => "desktop#export_table"
  
  get '/images/:name', :to => 'images#show', :as => :custom_image
  
  get "finishgroupapply", :to => "immigration/visa#finishing_application"
  get "deletepassportviadashboard/:id", :to => "desktop#destroy_passport", via: :delete, :as => :deletepassportviadashboard
  get "deletevisaviadashboard/:id", :to => "desktop#destroy_visa", via: :delete, :as => :deletevisaviadashboard
  get "deleteuserviadashboard/:id", :to => "desktop#destroy_user", via: :delete, :as => :deleteuserviadashboard
  
  get "visas/reapply/:id", :to => "immigration/visa#reapply"
  get "passports/reapply/:id", :to => "immigration/passport#reapply"
  
  get "dashboard/reference/list", :to => "reference#index"
  get "dashboard/reference/edit/:type/:id", :to => "reference#edit"
  match "/dashboard/reference/update_visafee", :to => "reference#update_visafee", via: :put, :as => :update_visafee_list
  match "/dashboard/reference/update_passportfee", :to => "reference#update_passportfee", via: :put, :as => :update_passportfee_list
  match "/dashboard/reference/update_signature", :to => "reference#update_reference", via: :put, :as => :update_reference_list
  
  get "passport/payment/:id", :to => "immigration/passport#payment"
  match "passport/payment/:id", to: "immigration/passport#update_payment", via: :patch, :as => :payment_proceed
  
  get "visas/compile/:ref_id", :to => "immigration/visa#show_receipt", :as => :visa_compile
  get "visas/payment/:ref_id", :to => "immigration/visa#payment"
  match "visas/payment/:ref_id", to: "immigration/visa#update_payment", via: :patch, :as => :visa_payment_proceed

  match "report/admin/:id/edit", to: "immigration/report#adminupdate", via: :patch, :as => :adminreportedit
  get "journal/show/:id", :to => "journal#retrieve_document_journal", :as => :document_journal
  get "samplepayment", :to =>"welcome#showsamplebayar"
  
  get "visas/group/:ref_id", to: "immigration/visa#group_recap"
  
  get "delete/user/passport/:id", :to => "immigration/passport#destroy", :as => :userdeletepassport
  get "delete/user/visa/:id", :to => "immigration/visa#destroy", :as => :userdeletevisa
  
  get "playground", :to => "playground#index"
  match "experiment", :to => "playground#experiment", via: :all
  

end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  include SimpleCaptcha::ControllerHelpers
  before_filter :authenticate_user!
  
  def index
    @case = Case.new
  end
  
  def info;  end
  
  def new;  end
  
  def show
    @case = Case.find(params[:id])
      respond_to do |format|
      format.html { render 'show' }
      format.json { render json: @case }
      format.xml { render xml: @case }
      format.pdf do
          render :pdf            => "Laporan Kasus WNI Bermasalah di Korea ["+"#{@case.full_name}"+"]_" + @case.id.to_s.upcase,
                 :disposition    => "inline", #{attachment, inline}                 
                 :template       => "cases/report.html.erb",
                 :layout         => "pdf_layout.html",
                 :encoding       => "utf8"                 
        end

    end
  end
  
  def formulirmasalahwni
    @case = Case.new
  end
  
  def masalahwni
    authorize! :showall, @cases, :message => 'Not authorized as an administrator.'
    @cases = Case.all.page(params[:page]).per(20)
    render layout: 'dashboard'
  end
  
  def create
    @case = [ Case.new(post_params) ]   
    tempcache = @case
    @case = @case[0]
    
    if @case.valid?
      if simple_captcha_valid?
          current_user.cases.push(tempcache)   
          current_user.save
          flash[:notice] = 'Aduan WNI Bermasalah di Korea telah dilaporkan ke sistem E-KBRI.'
          #render 'pasporconfirm.html.erb'
          render 'edit'
      else        
        @errors = { 'Kesalahan Kode Verifikasi' => 'Kode yang Anda Masukkan Salah'}
        render 'index'
      end
    else     
      @errors = @case.errors.messages
      render 'index'
    end 
  end
  
  def edit
    @case = Case.find(params[:id])
  end
  
  def update
    @case = Case.find(params[:id])
    if @case.update(post_params)
      if current_user.has_role? :admin or current_user.has_role? :moderator        
        redirect_to :back, :notice => "Data Kasus #{@case.full_name} telah berhasil diupdate."
      else
        redirect_to root_path, :notice => "Data Kasus #{@case.full_name} telah berhasil diperbaharui."
      end     
      
    else
      @errors = @case.errors.messages
      render 'edit'
    end
  end
  
  def destroy
    @case = Case.find(params[:id])
    if @case.delete
      redirect_to :back, :notice => "Data Kasus #{@case.full_name} telah berhasil dihapuskan dari sistem."
    else
      redirect_to :back, :notice => "Data Kasus #{@case.full_name} tidak dapat ditemukan."
    end
  end
  
  private  
    def post_params()
      params.require(:case).permit(
      :status, :full_name, :gender, :place_birth, :date_birth, :passport_no, :passport_place, :passport_date_from, :passport_date_to,  
      :address_id, :kelurahan_id, :kecamatan_id, :kabupaten_id, :provinsi_id, :phone_id, :visa_kr, :visa_kr_type, :visa_kr_from, :visa_kr_to, :address_kr, :city_kr, :province_kr, :phone_kr,         
      :company_kr, :company_address_kr, :company_city_kr, :company_province_kr, :company_phone_kr, :case_type, :case_description, :case_embassy_on_assistance, :case_embassy_post_assistance, 
      :case_embassy_staff_name, :case_remarks, :case_embassy_supporting_doc, :case_embassy_supporting_photo, :case_user_supporting_doc)
      
      #Notes: to add attribute/variable after POST params received, do
      #def post_params
      #  params.require(:post).permit(:some_attribute).merge(user_id: current_user.id)
      #end
    end
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/views/cases/info.html.erb
<div class="body" style="padding-top: 20px;">
	<div style="text-align: center;">
		<%= image_tag("/assets/images/garuda.png", height: '160', width: '160') %>
	</div>
	<div>
		<h2>LAPORAN & PERMINTAAN BANTUAN</h2>
		<p>Bagi warga negara Indonesia yang berada di Korea Selatan, apabila mengalami masalah/mengetahui ada permasalahan, 
		   silakan melaporkan kasusnya ke KBRI sehingga pihak KBRI dapat segera memberikan bantuan yang diperlukan.
		   Cara melaporkan kini sangat mudah karena bisa melalui sistem pelayanan elektronik KBRI.</p>
		<p>1. Isilah <b>formulir</b> permohonan bantuan yang disediakan melalui link di bawah ini.</p>
		<p>2. Untuk kemudahan pengenalan masalah dan sang korban, diharapkan dapat mengunggah <b>Foto atau Dokumen</b> petunjuk kasus.</p>
		
		<p>Selanjutnya, silahkan klik link formulir <span style="font-size: large;"> <%= link_to 'Laporan Permohonan Bantuan', lapormasalah_path %></span>.</p>
	</div>
</div>

app/views/cases/masalahwni.html.erb
<div class="body" style="padding-top: 20px;">
<div style="text-align: center;">
  <%= image_tag("/assets/images/garuda.png", height: '120', width: '120') %>
</div>
<h3 style="text-align: center;">Rekapitulasi Kasus WNI Bermasalah</h3>
<!--
<div class="span8">
	<div class="col-md-12 text-center">
		<div class="form-container">
				<p id="response-form">
					Find a user to lookup or modify. Simply key in their email or full name.
				</p>
				<%= form_for :user, url: searchuser_path, method: :post, remote: true, html: {id: "searchuser-form", class: "sky-form"} do |f| %>
					<%= f.text_field :name, class: "input-large", :placeholder => "Enter user's name." %>
					<%= f.text_field :email, class: "input-large", :placeholder => "Enter user's e-mail." %>
					<%=	f.submit 'Search', class: "btn btn-primary btn-mini btn-submit" %>
					<span id="loading" style="display: none;"><img src="/images/loadingBarBlue.gif" /></span>
				<% end %>
				<p id="response-form"></p>
		</div>
	</div>
</div>

<hr />
-->
<div class="span8">
	<table class="table table-condensed">
	  <thead>
	    <tr>
	      <th>Nama Lengkap</th>
	      <th>Tempat</th>
	      <th>Tanggal Aplikasi</th>
	      <th>Status Kasus</th>
	      <th></th>
	      <th></th>
	    </tr>
	  </thead>
	  <tbody>
	  <% @cases.each do |kasus| %>
	    <tr>
	      <td><%= link_to kasus.full_name, kasus %></td>
	      <td><%= kasus.province_kr %></td>
	      <td><%= kasus.updated_at.strftime("%-d %b %y") %></td>
	      <td><%= kasus.status %></td>
	      <td><%= link_to("Edit Kasus", edit_case_path(kasus), :class => 'btn btn-mini btn-primary') %></td>
	      <td><%= link_to("Delete Kasus", deletemasalahwni_path(kasus), :class => 'btn btn-mini btn-danger') %></td>
	    </tr>
	  <% end %>
	  </tbody>
	</table>
	  <%= paginate @cases %>
</div>

app/views/cases/show.html.erb
<div class="body" style="padding-top: 20px;">
			<div style="text-align: center;">
			  <%= image_tag("/assets/images/garuda.png", height: '160', width: '160') %>
			</div>
			
			<% unless @errors.nil? %>
			<h2 style="color:white;background:red;">Laporan Gagal. Silahkan cek pesan dibawah ini</h2>
				<div style="padding:4px;color:red;font-size:10pt;">
					<% @errors.each do |fs| %>
						<%= simple_format(fs[0].to_s + " = " + fs[1].to_s + "\n")  %>
					<%end%>
					<br />
					Silahkan Upload File - File anda kembali jika ada.
				</div>
			<%end%>	
				
			<!-- Red color scheme -->
			<%= simple_form_for @case, url: case_path(@case), :method => :patch, :html => { :class => "sky-form", :multipart => true } do |f| %>
				<header>Rekap Laporan Individual Permasalahan WNI di Korea Selatan</header>				
				<fieldset>
					<div class="row">
						<section class="col col-3">
							<p><b>Jenis Masalah</b></p>
							<%= @case.case_type.upcase %>
						</section>
						<% if current_user.has_role? :admin or :moderator %>
						<section class="col col-3">
							<p><b>Status Masalah</b></p>
							<%= @case.status.capitalize %>
						</section>
						<section class="col col-6">
							<p><b>Konklusi Masalah</b></p>
							<%= @case.case_remarks.capitalize %>				
						</section>
						<% end %>
					</div>
					
					<div class="row">
						<section class="col col-9">
							<p><b>Deskripsi Masalah</b></p>
							<%= @case.case_description.capitalize %>				
						</section>
						
						<% if current_user.has_role? :admin or :moderator %>
						<section class="col col-3">
							<p><b>Staff KBRI</b></p>
							<%= @case.case_embassy_staff_name.titleize %>
						</section>
						<% end %>
					</div>	
					
					<% if current_user.has_role? :admin or :moderator %>
					<div class="row">
						<h4>Informasi Penanganan</h4>
						<hr /><br />
						<section class="col col-6">
							<p><b>Bantuan KBRI saat Masalah</b></p>
							<%= @case.case_embassy_on_assistance.capitalize %>				
						</section>
						
						<section class="col col-6">
							<p><b>Bantuan KBRI sesudah Masalah</b></p>
							<%= @case.case_embassy_post_assistance.capitalize %>				
						</section>
					</div>
					<% end %>
									
				</fieldset>
				
				<fieldset>
					<h3>Profil WNI Bermasalah</h3>	
					<hr /><br />
					<div class="row">
						<section class="col col-4">
							<p><b>Nama Lengkap</b></p>
							<%= @case.full_name.titleize %>
						</section>	
						<section class="col col-2">
							<p><b>Jenis Kelamin</b></p>
							<%= @case.gender.upcase %>
						</section>							
						
						<section class="col col-3">
							<p><b>Tempat Lahir</b></p>	
							<%= @case.place_birth.capitalize %>
						</section>

						<section class="col col-3">
							<p><b>Tanggal Lahir</b></p>	
							<%= @case.date_birth.strftime("%-d %b %y") %>
							<div class="note"><strong>Format : </strong>YYYY/MM/DD</div>
						</section>
		
					</div>	
					
					<div class="row">
						
						<section class="col col-3">
							<p><b>Nomor Paspor</b></p>	
							<%= @case.passport_no.upcase %>
						</section>
						
						<section class="col col-3">
							<p><b>Tanggal Terbit Paspor</b></p>
							<%= @case.passport_date_from.strftime("%-d %b %y") %>
							<div class="note"><strong>Format : </strong>YYYY/MM/DD</div>
						</section>
						
						<section class="col col-3">
							<p><b>Tanggal Habis Berlaku Paspor</b></p>
							<%= @case.passport_date_to.strftime("%-d %b %y") %>
							<div class="note"><strong>Format : </strong>YYYY/MM/DD</div>
						</section>					
						
						
						<section class="col col-3">
							<p><b>Kantor Imigrasi</b></p>
							<%= @case.passport_place %>							
						</section>
						
					</div>				
				</fieldset>
				
				<fieldset>
					<h3>Alamat & Keluarga di Indonesia</h3>	
					<hr /><br />
					<div class="row">
				    
						<section class="col col-6">
							<p><b>Alamat di Indonesia</b></p>
							<%= @case.address_id.titleize %>
						</section>
						
						<section class="col col-6">
							<p><b>Kelurahan/Desa</b></p>
							<%= @case.kelurahan_id.titleize %>
						</section>
					
				    </div>
				    
				    <div class="row">
						
						<section class="col col-3">
							<p><b>Kecamatan</b></p>
							<%= @case.kecamatan_id.titleize %>
						</section>
						
						<section class="col col-3">
							<p><b>Kabupaten/Kota</b></p>
							<%= @case.kabupaten_id.titleize %>
					   	</section>
					  
					   <section class="col col-3">
						 <p><b>Propinsi</b></p>
						 <%= @case.provinsi_id.titleize %>
					   </section>
					
					   <section class="col col-3">
							<p><b>No Telepon di Indonesia</b></p>
							<%= @case.phone_id %>
					   </section>
					</div>
				</fieldset>
				
				<fieldset>
					<h3>Detail di Korea</h3>	
					<hr /><br />
					<div class="row">
						<section class="col col-4">
							<p><b>Pekerjaan di Korea</b></p>
							<%= @case.visa_kr.upcase %>
						</section>
						
						<section class="col col-4">
							<p><b>Keterangan Pekerjaan</b></p>
							<%= @case.visa_kr_type.capitalize %>
						</section>
						
						<section class="col col-4">
							<p><b>No Telepon di Korea</b></p>
							<%= @case.phone_kr %>
						</section>
						
				  </div>
					
					<div class="row">
						<section class="col col-6">
							<p><b>Alamat Tinggal di Korea</b></p>
							<%= @case.address_kr.capitalize %>						
						</section>
						
						<section class="col col-3">
							<p><b>Kota</b></p>
							<%= @case.city_kr.capitalize %>
						</section>
						
						<section class="col col-3">
							  <p><b>Propinsi</b></p>
							  <%= @case.province_kr.capitalize %>							
						</section>

					</div>
					
					<div class="row">
						
						<section class="col col-3">
							<p><b>Ijin Tinggal/Visa Diterbitkan</b></p>
							<%= @case.visa_kr_from.strftime("%-d %b %y") %>
						</section>
						
						<section class="col col-3">
							  <p><b>Ijin Tinggal/Visa Habis Berlaku</b></p>
							  <%= @case.visa_kr_to.strftime("%-d %b %y") %>							
						</section>

					</div>

				</fieldset>		
				
				<fieldset>
					<h3>Detail Perusahaan/Institusi/Sekolah</h3>	
					<hr /><br />
					<div class="row">
						<section class="col col-6">
							<p><b>Nama Perusahaan/Sekolah/Instansi</b></p>
							<%= @case.company_kr.capitalize %>				
						</section>
						
						<section class="col col-6">
							<p><b>Alamat Perusahaan/Sekolah/Instansi</b></p>
							<%= @case.company_address_kr %>				
						</section>
					</div>	
					
					<div class="row">
						<section class="col col-3">
							<p><b>Kota</b></p>
							<%= @case.company_city_kr.capitalize %>
						</section>
						
						<section class="col col-3">
							  <p><b>Propinsi</b></p>
							  <%= @case.company_province_kr.capitalize %>							
						</section>
						
						<section class="col col-6">
							<p><b>No Telepon Perusahaan/Sekolah/Instansi</b></p>
							<%= @case.company_phone_kr %>
						</section>
						
					</div>	
				</fieldset>
				
				<fieldset class="no-print">
				<% if @case.case_embassy_supporting_photo.exists? && (current_user.has_role? :admin or current_user.has_role? :moderator) %>
				    <section class="col col-4">
				    	<p>Foto dari KBRI</p>
							<%= image_tag @case.case_embassy_supporting_photo.url(:thumb) %>
							<% if current_user.has_role? :admin or current_user.has_role? :moderator %>
								<%= link_to 'Download', @case.case_embassy_supporting_photo.url(:original, false), target: "_blank" %>
							<%end%>
					</section>
				<% end %>
				<% if @case.case_embassy_supporting_doc.exists? && (current_user.has_role? :admin or current_user.has_role? :moderator) %>
				    <section class="col col-4">
				    	<p>Dokumen dari KBRI</p>
							<%= image_tag("/assets/images/doc.gif", height: '120', width: '120') %>
							<% if current_user.has_role? :admin or current_user.has_role? :moderator %>
								<%= link_to 'Download', @case.case_embassy_supporting_doc.url(:original, false), target: "_blank" %>
							<%end%>
					</section>
				<% end %>
				<% if @case.case_user_supporting_doc.exists? %>
				    <section class="col col-4">
				    	<p>Foto dari Pelapor</p>
							<%= image_tag @case.case_user_supporting_doc.url(:thumb) %>
							<% if current_user.has_role? :admin or current_user.has_role? :moderator %>
								<%= link_to 'Download', @case.case_user_supporting_doc.url(:original, false), target: "_blank" %>
							<%end%>
					</section>
				<% end %>
				<% if (!@case.case_embassy_supporting_photo.exists? && !@case.case_embassy_supporting_doc.exists?) and !@case.case_user_supporting_doc.exists? %>
					<!--
					<section class="col col-6">
							<label class="label"><b>Foto atau Dokumen Pendukung</b></label>
							<label for="file" class="input input-file">
								<div class="button">									
									<%= f.input_field :case_user_supporting_doc, as: :file, class: 'fileplaceholder' %>Unggah</div>
									<input type="text" name="userdocpath" readonly="readonly" />
							</label>
							<div class="note">
								<strong>Catatan : </strong>Ukuran Maks. 2MB<br />
							</div>
					</section>	
					<section class="col col-6">
							<label class="label"><b>Foto atau Dokumen Pendukung (oleh staff KBRI)</b></label>
							<label for="file" class="input input-file">
								<div class="button">									
									<%= f.input_field :case_embassy_supporting_doc, as: :file, class: 'fileplaceholder' %>Unggah</div>
									<input type="text" name="embassydocpath" readonly="readonly" />
							</label>
							<div class="note">
								<strong>Catatan : </strong>Ukuran Maks. 2MB<br />
							</div>
					</section>	
					-->
					<section class="col col-6"><p><b>Foto atau Dokumen Pendukung tidak ditemukan.</b></p></section>
				<% end %>
				</fieldset>
				
				<!-- 
				<fieldset style="text-align:justify;" class="no-print">
					<h4>Disclaimer</h4>
					<hr /><br />
					<p>Dengan mengisi form ini Saya menyatakan bahwa semua data yang diisikan merupakan informasi yang sebenar-benarnya. 
						Segala kesalahan informasi yang dapat menyebabkan kerugian adalah tanggung jawab Saya dan tidak dapat di tangguhkan pada pihak lain. 
						KBRI Seoul dan staff terkait dapat menolak/meminta perubahan data dan informasi terkait permohonan jika tidak sesuai dengan syarat dan ketentuan.
					</p>

				</fieldset>
				-->

				<footer class="no-print">
					<button type="button" class="button button-primary" onclick="window.print(); return false;">Print Dokumen Ini</button>
					<button type="button" class="button button-secondary" onclick="window.close();">Tutup Dokumen Ini</button>
					<button type="button" class="button button-secondary" onclick="location.href='<%= site_url %>';">Kembali ke Panel Utama</button>
					<button type="button" class="button button-primary" onclick="location.href='<%= edit_case_path %>';">Edit Ulang Dokument Ini</button>
				</footer>
			<% end %>
			<!--/ Red color scheme -->			
</div>

<script type="text/javascript">
			$(function()
			{
				$('input[type=text]').keyup(function() {
				    $(this).val($(this).val().toUpperCase());
				});
				//$('textarea').keyup(function() {
				//    $(this).val($(this).val().toUpperCase());
				//});
				$('#passport_application_reason').change(function(){
					if($(this).val() == 'lainnya'){
						$('#pasporsebelumnya').hide();						
					}else{												
						$('#pasporsebelumnya').show();
					}
				});	
				// Regular datepicker
				$('.datePick').datepicker({
					dateFormat: 'yy/mm/dd',
					prevText: '<i class="icon-chevron-left"></i>',
					nextText: '<i class="icon-chevron-right"></i>',
					changeMonth: true,
      				changeYear: true,
      				yearRange: '1900:2040'
				});
				
				$('.fileplaceholder').change(function(){					
					filename = $(this).val();
					$(this).parent().next().val(filename.split("\\").pop());
				});
				
			});			
</script>