config/routes.rb
EKbri::Application.routes.draw do

  resources :visas, controller: 'immigration/visa'
  resources :visafamilys, controller: 'immigration/visafamily'
  resources :visagroups, controller: 'immigration/visagroup'
  resources :passports, controller: 'immigration/passport'
  resources :reports, controller: 'immigration/report'  
  resources :cases
    
  get "dashboard/protocols", :to => "protocol#index"
  
  authenticated :user do
    root to: 'welcome#index', as: :authenticated_root
  end

  unauthenticated do
    root to: "welcome#index"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  devise_scope :user do 
    get "/users/sign_out" => "devise/sessions#destroy" 
  end 
  
  resources :users
  get "searchuser", :to => "users#search"
  
  get "infovisas", :to => "immigration/visa#info"   
  get "infopassports", :to => "immigration/passport#info"
  get "inforeports", :to => "immigration/report#info"
  get "bantuan", :to => "cases#info"
  get "lapormasalah", :to => "cases#index"
  get "marriage/info", :to => "immigration/marriage#info"
  
  get "overview", :to => "immigration/flow#systemoverview"
  get "payment", :to => "immigration/flow#systempayment"
  get "visaflow", :to => "immigration/flow#visa"   
  get "visadocs", :to => "immigration/flow#visadocs"
  get "passportflow", :to => "immigration/flow#passport"
  get "passportdocs", :to => "immigration/flow#passportdocs"
  get "reportflow", :to => "immigration/flow#report"
  get "reportdocs", :to => "immigration/flow#reportdocs"

  get "finishgroupapply", :to => "immigration/visa#finishing_application"
  get "visas/reapply/:id", :to => "immigration/visa#reapply"
  get "passports/reapply/:id", :to => "immigration/passport#reapply"
  
  get "dashboard/index"
  get "dashboard/masalahwni", :to => "cases#masalahwni"
  get "dashboard/formulirmasalahwni", :to => "cases#formulirmasalahwni", as: "formulirmasalahwni"
  match "dashboard/deletemasalahwni/:id", to: "cases#destroy", as: "deletemasalahwni", via: :get

  get "dashboard/counsel"
  get "dashboard/immigration"
  get "dashboard/immigration/:document" => "dashboard#immigration" 
  get "dashboard/employment_indonesia"
  get "dashboard/employment_korea"
  get "dashboard/tabulation"
  get "dashboard/statistics"
  get "dashboard", :to => "dashboard#index"
  
  get "welcome/concept"
  get "concept/index"
  get "concept", :to => "concept#index"
  
  match "statistics", :to => "statistics#index", via: :get
  
  get "visa/show/all", :to => "desktop#show_all_sisari"
  get "lapordiri/show/all", :to => "desktop#show_all_lapordiri"
  get "lapordiri/show/history/:user_id", :to => "desktop#show_all_lapordiri_history"
  get "passport/show/all", :to => "desktop#show_all_spri"
  get "case/list/all", :to => "desktop#show_all_cases"
  get "dashboard/service/:document", :to => "dashboard#immigration"
  get "admin/service/:document/:id", :to => "dashboard#immigration"
  get "dashboard/syncpanel", :to => "dashboard#syncpanel"
  get "journal/list/all", :to => "journal#show_all_journal"

  
  
  match "passport/tospri/:id", to: "desktop#exec_toSPRI", via: :post
  match "visa/tosisari/:id", to: "desktop#exec_toSisari", via: :post
  
  get "passports/:id/check", :to => "immigration/passport#check"
  get "visas/:id/check", :to => "immigration/visa#check"
  get "reports/:id/check", :to => "immigration/report#check"
  get "reports/:whosign/:id", :to => "immigration/report#show"
  get "reports/user/print/:id", :to => "immigration/report#show"
  
  get "protocol/synccloudtolocal/:collection", :to => "protocol#syncCollectionCloudtoLocal"
  get "protocol/syncdbcomplete", :to => "protocol#syncDBComplete"
  

  match "report/findbynameandbirth", to: "immigration/report#findbyNameandBirth", via: :get
  
  get "report/panel/periodical", :to => "dashboard#periodical_reporting"
  get "report/panel/periodical_printed_based", :to => "dashboard#periodical_reporting_printed_based"
  match "report/generate/periodical", to: "dashboard#generate_periodical_reporting", via: :post  
  match "report/generate/periodical_printed_based", to: "dashboard#generate_periodical_reporting_printed_based", via: :post
  
  get "export/table/:doc", :to => "desktop#export_table"
  
  get '/images/:name', :to => 'images#show', :as => :custom_image
  
  get "finishgroupapply", :to => "immigration/visa#finishing_application"
  get "deletepassportviadashboard/:id", :to => "desktop#destroy_passport", via: :delete, :as => :deletepassportviadashboard
  get "deletevisaviadashboard/:id", :to => "desktop#destroy_visa", via: :delete, :as => :deletevisaviadashboard
  get "deleteuserviadashboard/:id", :to => "desktop#destroy_user", via: :delete, :as => :deleteuserviadashboard
  
  get "visas/reapply/:id", :to => "immigration/visa#reapply"
  get "passports/reapply/:id", :to => "immigration/passport#reapply"
  
  get "dashboard/reference/list", :to => "reference#index"
  get "dashboard/reference/edit/:type/:id", :to => "reference#edit"
  match "/dashboard/reference/update_visafee", :to => "reference#update_visafee", via: :put, :as => :update_visafee_list
  match "/dashboard/reference/update_passportfee", :to => "reference#update_passportfee", via: :put, :as => :update_passportfee_list
  match "/dashboard/reference/update_signature", :to => "reference#update_reference", via: :put, :as => :update_reference_list
  
  get "passport/payment/:id", :to => "immigration/passport#payment"
  match "passport/payment/:id", to: "immigration/passport#update_payment", via: :patch, :as => :payment_proceed
  
  get "visas/compile/:ref_id", :to => "immigration/visa#show_receipt", :as => :visa_compile
  get "visas/payment/:ref_id", :to => "immigration/visa#payment"
  match "visas/payment/:ref_id", to: "immigration/visa#update_payment", via: :patch, :as => :visa_payment_proceed

  match "report/admin/:id/edit", to: "immigration/report#adminupdate", via: :patch, :as => :adminreportedit
  get "journal/show/:id", :to => "journal#retrieve_document_journal", :as => :document_journal
  get "samplepayment", :to =>"welcome#showsamplebayar"
  
  get "visas/group/:ref_id", to: "immigration/visa#group_recap"
  
  get "delete/user/passport/:id", :to => "immigration/passport#destroy", :as => :userdeletepassport
  get "delete/user/visa/:id", :to => "immigration/visa#destroy", :as => :userdeletevisa
  
  get "playground", :to => "playground#index"
  match "experiment", :to => "playground#experiment", via: :all
  

end

app/controllers/immigration/flow_controller.rb
class Immigration::FlowController < ApplicationController
  
  def systemoverview
  end
  
  def systempayment
  end
  
  def visa
  end
  
  def visadocs
  end
  
  def passport
  end
  
  def passportdocs
  end
  
  def report
  end
  
  def reportdocs
  end
  
end

app/controllers/immigration/marriage_controller.rb
class Immigration::MarriageController < ApplicationController
  
  def index
    
  end
  
  def info
    
  end
  
  def create
    
  end
  
  def update
    
  end
  
  def edit
    
  end
  
  def show
    
  end
  
end

app/controllers/immigration/passport_controller.rb
class Immigration::PassportController < ApplicationController
  include SimpleCaptcha::ControllerHelpers

  before_filter :authenticate_user!
  #GET /passport  

  @@VIPACOUNTERDEF = 6600

  
  def index
    #1 Person, 1 Application in 5 years
    #if Passport.where(user_id: current_user).count > 0
    #    redirect_to edit_passport_path(current_user)
    #end
    #We comment this as we want to enable multiple paspors and/or SPLPs
    @passport = Passport.new
  end
  
  def reapply
    redirect_to root_path, :notice => 'You have successfully notified The Embassy staff to recheck your previously incomplete application.'
  end
  
  #GET /new
  def new
  
  end
  

  def check
    @passport = Passport.find(params[:id])    
    render layout: "dashboard"    
  end
  
  def payment
    @passport = Passport.find(params[:id])
  end

  #GET passport/:id
  def show
    @passport = Passport.find(params[:id])
      respond_to do |format|
      format.html { render 'edit' }
      format.json { render json: @passport }
      format.xml { render xml: @passport }
      format.pdf do
          render :pdf            => "Receipt of Passport Application ["+"#{current_user.full_name}"+"]_" + @passport.ref_id,
                 :disposition    => "attachment", #{attachment, inline}                 
                 :template       => "immigration/passport/pasporpayment.html.erb",
                 :layout         => "pdf_layout.html",
                 :encoding       => "utf8"                 
        end

    end
  end
  
  #POST /passport

  def create       
    @passport = [ Passport.new(post_params) ]
    #current_user.passports = @passport    
    tempcache = @passport
    @passport = @passport[0]
    
    if @passport.valid?
      if simple_captcha_valid?
          current_user.passports.push(tempcache)   
          current_user.save
          UserMailer.passport_received_email(@passport).deliver
          current_user.journals.push(Journal.new(:action => 'Created', :model => 'Passport', :method => 'Insert', :agent => request.user_agent, :record_id => @passport.id, :ref_id => @passport.ref_id ))
          flash[:notice] = 'Pengurusan aplikasi paspor anda, berhasil!'
          render 'pasporconfirm.html.erb'
      else        
        @errors = { 'Secret Code' => 'Wrong Code Entered'}
        render 'index'
      end
    else     
      @errors = @passport.errors.messages
      render 'index'
    end    
    

    #debugging
    #logger.debug "We are inspecting PASSPORT PROCESSING PARAMS as follows:"
    #puts params.inspect
    #puts @passport.inspect
  end
  
  #GET /passport/:id/edit
  def edit
    #@passport = Passport.find_by(user_id: params[:id])
    @passport = Passport.find(params[:id])
  end
  
  #PATCH, PUT /passport/:id
  def update
    @passport = Passport.find(params[:id])
    #@passport = Passport.find_by(user_id: params[:id])
    if @passport.update(post_params)
      
      current_user.journals.push(Journal.new(:action => @passport.status, :model => 'Passport', :method => 'Update', :agent => request.user_agent, :record_id => @passport.id, :ref_id => @passport.ref_id ))
      if current_user.has_role? :admin or current_user.has_role? :moderator        
        UserMailer.admin_update_passport_email(@passport).deliver
        redirect_to :back, :notice => 'A Passport Application Data has been updated'
      else
        redirect_to root_path, :notice => 'Anda telah berhasil memperbaharui data pengurusan paspor anda!'
      end     
      
    else
      @errors = @passport.errors.messages
      render 'edit'
    end
  end
  

  def update_payment 
    @passport = Passport.find(params[:id])
    if @passport.update(post_params)    
      current_user.journals.push(Journal.new(:action => @passport.status, :model => 'Passport', :method => 'Update', :agent => request.user_agent, :record_id => @passport.id, :ref_id => @passport.ref_id  ))  
      redirect_to root_path, :notice => 'Data Pembayaran anda berhasil disimpan!'
    else
      @errors = @passport.errors.messages
      render 'payment'
    end
  end
  

  #DELETE /passport/:id
  def destroy 
   @passport = Passport.find(params[:id])
    reference = @passport.ref_id
    if @passport.delete
      current_user.journals.push(Journal.new(:action => 'Removed', :model => 'Passport', :method => 'Delete', :agent => request.user_agent, :record_id => params[:id], :ref_id => reference ))
      redirect_to :back, :notice => "Paspor dengan No. Ref. #{reference} telah berhasil dihapuskan dari sistem."
    else
      redirect_to :back, :notice => "Paspor No. Ref. #{reference} tidak dapat ditemukan."
    end
  end    
  
  private  
    def post_params()
      params.require(:passport).permit(:application_type, :application_reason, :paspor_type, :full_name, :height, :kelamin, :placeBirth, :dateBirth,              
      :citizenship_status, :lastPassportNo, :dateIssued, :placeIssued, :jobStudyInKorea, :jobStudyTypeInKorea, :jobStudyOrganization, :jobStudyAddress, 
      :phoneKorea, :addressKorea, :cityKorea, :phoneIndonesia, :addressIndonesia, :kelurahanIndonesia, :kecamatanIndonesia, :kabupatenIndonesia, :dateArrival, :sendingParty, :photo, :status, :slip_photo, :payment_date, :arc, :dateIssuedEnd, :immigrationOffice, :sponsor_address_prov_kr, :sponsor_address_prov_id, :supporting_doc, :supporting_doc_2, :supporting_doc_3, :supporting_doc_4, :comment, :pickup_office, :pickup_date)

    end
    #Notes: to add attribute/variable after POST params received, do
    #def post_params
    #  params.require(:post).permit(:some_attribute).merge(user_id: current_user.id)
    #end
    def reference_no_passport
      time = Time.new
      coded_date = time.strftime("%y%m%d")
      ref_id = 'D'+coded_date+generate_string(3)
    end
    def generate_string(length=5)
      chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ123456789'
      password = ''
      length.times { |i| password << chars[rand(chars.length)] }
      password = password.upcase
    end
end

app/helpers/immigration/marriage_helper.rb
module Immigration::MarriageHelper
end

app/helpers/immigration/passport_helper.rb
module Immigration::PassportHelper
end

app/helpers/immigration/report_helper.rb
module Immigration::ReportHelper
end

app/helpers/immigration/visa_helper.rb
module Immigration::VisaHelper
end

app/views/immigration/visa/edit.html.erb
<%= 
render 'forms/visa_edit'  
%>

app/views/immigration/visa/index.html.erb
<%= render 'forms/visa'  %>

app/views/immigration/visa/payment.html.erb
<div class="body" style="padding-top: 20px;">
			<div style="text-align: center;">
			  <%= image_tag("/assets/images/garuda.png", height: '160', width: '160') %>
			</div>
			
			<% unless @errors.nil? %>
			<h2 style="color:white;background:red;">Penyimpanan Gagal. Silahkan cek pesan dibawah ini</h2>
				<div style="padding:4px;color:red;font-size:10pt;">
					<% @errors.each do |fs| %>
						<%= simple_format(fs[0].to_s + " = " + fs[1].to_s + "\n")  %>
					<%end%>
				</div>
			<%end%>
				
			<!-- Red color scheme -->
			<%= simple_form_for @visagrouppayment, url: visa_payment_proceed_path(), :method => :patch, :html => { :class => "sky-form", :multipart => true } do |f| %>
				<header>Visa Application Payment Confirmation</header>
				<fieldset>
					<div class="row">
						<section class="col col-6">
							<label class="label">Visa Reference No.:</label>
							<b><%= @visas.first.ref_id %></b>
						</section>						
					</div>
					<center><table cellpadding="2" cellspacing="2" width="600">							
							<tr>
								<td>Application Type</td>
								<td>
									<% if @visas.count > 1 %>
										Group/Family Visa : <%= @visas.count %> Person(s)
									<% else %>
										Individual Visa
									<% end %></td>
							</tr>
							<tr>
								<td>Grantee Detail</td>
								<td><% totalfee = 0
									 @visas.each do |row| %>
										<b><%= row.first_name + ' ' + row.last_name %></b> (<%= row.category_type %>)  :  <%= (row.status=='Verified' || row.status == "Paid" || row.status == "Approved" || row.status == 'Printed' )? Visafee.where(:id => row.visafee_ref).first.name_of_visa  : 'Under Review' %><br />
										
										<% totalfee += Visafee.find(row.visafee_ref).fee_of_visa %>
									<% end %>
								</td>
							</tr>
					</table></center>
				</fieldset>		
				
				<fieldset style="text-align:center;">
					<h6><b>Total Fee </b></h6><Br />
					<h1>$<%= totalfee %></h1><Br />					
					<p >Please make your payment through <b>KEB Bank (외환은행)</b>. Indonesian Embassy in Seoul account <b>650-005012-179</b> proceed with <b>Dollar currency payment (Foreign Currency Deposit Slip / 외화예금전표 )</b>. Currency : <b>USD</b></p>
					<br />
					<p><b>Please rewrite the Reference Number to the Depositor Name section in the payment slip. Example : <a target="_blank" href="/samplepayment">Payment slip</a></b></p>
					<p><b>Reminder</b> : The date is the transaction date as in the payment slip</p>
				</fieldset>	
				
				<fieldset style='background:#FFCC00;'>
					<h4>Payment Confirmation</h4>
					<br />
					<div class="row">
						<section class="col col-6">
							<label class="label" style='background:#FFCC00;'> Scan/Digital Copy of Payment Receipt</label>
							<label for="file" class="input input-file">
								<div class="button">
									<%= f.input_field :slip_photo, as: :file, class: 'fileplaceholder' %>Upload</div>
									<input type="text" readonly="readonly" />
							</label>
							<% if @visagrouppayment.slip_photo.exists? %>
												
								<% if current_user.has_role? :admin or current_user.has_role? :moderator %>
									<%= link_to 'Download Slip', @visagrouppayment.slip_photo.url(:original, false), target: "_blank" %>
								<%end%>
											
							<%end%>
							<div class="note"><strong>Catatan:</strong> Hanya berkas JPG/JPEG/PNG/PDF. Ukuran Maks. 2MB</div>
						</section>	
						<section class="col col-6">
							<label class="label" style='background:#FFCC00;'>Payment Date</label>	
							<label class="input">
									<i class="icon-append icon-calendar"></i>
									<%= f.input_field :payment_date, class: 'datePick' %>
							</label>
							<div class="note"><b>Reminder</b> : The date is the transaction date as in the payment slip</div>
						</section>		
					</div>
				</fieldset>			
				<fieldset>
					<h4>Pickup Location </h4>
					<br />
					<section class="col col-6">
							<label class="label">Office</label>	
							<label class="select">
								<%= f.input_field :pickup_office, :required => true, :selected => 'seoul',
								collection: { 'Indonesian Embassy Seoul Office' => 'seoul', 
								          	  'Indonesian Consulate Busan Branch' => 'busan' } %>
							<i></i>
							</label>
							<div class="note">Find out the location by clicking this link : <a target="_blank" href="http://kbriseoul.kr/kbriseoul/index.php/en/contact-us">Office Location</a></div>
					</section>	
						
				</fieldset>	
				<fieldset style="text-align:justify;">
					<h4>Disclaimer</h4>
					<hr /><br />
					<p>Upon submitting this form I am fully aware that every data provided are truthful and correct information. Any misleading or incorrect information which may cause detrimental effect is taken as my responsibility and can not be delegated to any other party. False information may result to sanction or considered as criminal and will be taken action according to the implemented Law</p>
					<br />
					<p>The time of payment confirmation to pickup schedule may consume at least 3 (Three) days. Payment confirmation result will be sent to email or may be verified through this website. </p>
					<br />
					<p><b>Please bring the REAL payment confirmation slip along with the application receipt during the pickup time</b></p>
				</fieldset>
				<footer>
					<%= f.input_field :status, :value => 'Paid', as: :hidden %>
					<%= f.input_field :ref_id, :value => @visas.first.ref_id, as: :hidden %>
					<button type="submit" class="button">Save</button>
					<button type="button" class="button button-secondary" onclick="window.history.back();">Back</button>
				</footer>
			<% end %>
			<!--/ Red color scheme -->			
</div>



<script type="text/javascript">
			$(function()
			{				
				// Regular datepicker
				$('.datePick').datepicker({
					dateFormat: 'yy/mm/dd',
					prevText: '<i class="icon-chevron-left"></i>',
					nextText: '<i class="icon-chevron-right"></i>',
					changeMonth: true,
      				changeYear: true,
      				yearRange: '1900:2040'
				});
				
				$('.fileplaceholder').change(function(){					
					filename = $(this).val();
					$(this).parent().next().val(filename.split("\\").pop());
				});
				
			});			
</script>

app/views/immigration/visa/visaconfirm.html.erb
<style>
/* ------------------------------------- 
		GLOBAL 
------------------------------------- */
* { 
	margin:0;
	padding:0;
}
* { font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif; }

img { 
	max-width: 100%; 
}
.collapse {
	margin:0;
	padding:0;
}
body {
	-webkit-font-smoothing:antialiased; 
	-webkit-text-size-adjust:none; 
	width: 100%!important; 
	height: 100%;
}


/* ------------------------------------- 
		ELEMENTS 
------------------------------------- */
a { color: #2BA6CB;}

.btn {
	text-decoration:none;
	color: #FFF;
	background-color: #666;
	padding:10px 16px;
	font-weight:bold;
	margin-right:10px;
	text-align:center;
	cursor:pointer;
	display: inline-block;
}

p.callout {
	padding:15px;
	background-color:#ECF8FF;
	margin-bottom: 15px;
}
.callout a {
	font-weight:bold;
	color: #2BA6CB;
}

table.social {
/* 	padding:15px; */
	background-color: #ebebeb;
	
}
.social .soc-btn {
	padding: 3px 7px;
	font-size:12px;
	margin-bottom:10px;
	text-decoration:none;
	color: #FFF;font-weight:bold;
	display:block;
	text-align:center;
}
a.fb { background-color: #3B5998!important; }
a.tw { background-color: #1daced!important; }
a.gp { background-color: #DB4A39!important; }
a.ms { background-color: #000!important; }

.sidebar .soc-btn { 
	display:block;
	width:100%;
}

/* ------------------------------------- 
		HEADER 
------------------------------------- */
table.head-wrap { width: 100%;}

.header.container table td.logo { padding: 15px; }
.header.container table td.label { padding: 15px; padding-left:0px;}


/* ------------------------------------- 
		BODY 
------------------------------------- */
table.body-wrap { width: 100%;}


/* ------------------------------------- 
		FOOTER 
------------------------------------- */
table.footer-wrap { width: 100%;	clear:both!important;
}
.footer-wrap .container td.content  p { border-top: 1px solid rgb(215,215,215); padding-top:15px;}
.footer-wrap .container td.content p {
	font-size:10px;
	font-weight: bold;
	
}


/* ------------------------------------- 
		TYPOGRAPHY 
------------------------------------- */
h1,h2,h3,h4,h5,h6 {
font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; line-height: 1.1; margin-bottom:15px; color:#000;
}
h1 small, h2 small, h3 small, h4 small, h5 small, h6 small { font-size: 60%; color: #6f6f6f; line-height: 0; text-transform: none; }

h1 { font-weight:200; font-size: 44px;}
h2 { font-weight:200; font-size: 37px;}
h3 { font-weight:500; font-size: 27px;}
h4 { font-weight:500; font-size: 23px;}
h5 { font-weight:900; font-size: 17px;}
h6 { font-weight:900; font-size: 14px; text-transform: uppercase; color:#444;}

.collapse { margin:0!important;}

p, ul { 
	margin-bottom: 10px; 
	font-weight: normal; 
	font-size:14px; 
	line-height:1.6;
}
p.lead { font-size:17px; }
p.last { margin-bottom:0px;}

ul li {
	margin-left:5px;
	list-style-position: inside;
}

/* ------------------------------------- 
		SIDEBAR 
------------------------------------- */
ul.sidebar {
	background:#ebebeb;
	display:block;
	list-style-type: none;
}
ul.sidebar li { display: block; margin:0;}
ul.sidebar li a {
	text-decoration:none;
	color: #666;
	padding:10px 16px;
/* 	font-weight:bold; */
	margin-right:10px;
/* 	text-align:center; */
	cursor:pointer;
	border-bottom: 1px solid #777777;
	border-top: 1px solid #FFFFFF;
	display:block;
	margin:0;
}
ul.sidebar li a.last { border-bottom-width:0px;}
ul.sidebar li a h1,ul.sidebar li a h2,ul.sidebar li a h3,ul.sidebar li a h4,ul.sidebar li a h5,ul.sidebar li a h6,ul.sidebar li a p { margin-bottom:0!important;}



/* --------------------------------------------------- 
		RESPONSIVENESS
		Nuke it from orbit. It's the only way to be sure. 
------------------------------------------------------ */

/* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
.container {
	display:block!important;
	max-width:600px!important;
	margin:0 auto!important; /* makes it centered */
	clear:both!important;
}

/* This should also be a block element, so that it will fill 100% of the .container */
.content {
	padding:15px;
	max-width:600px;
	margin:0 auto;
	display:block; 
}

/* Let's make sure tables in the content area are 100% wide */
.content table { width: 100%; }


/* Odds and ends */
.column {
	width: 300px;
	float:left;
}
.column tr td { padding: 15px; }
.column-wrap { 
	padding:0!important; 
	margin:0 auto; 
	max-width:600px!important;
}
.column table { width:100%;}
.social .column {
	width: 280px;
	min-width: 279px;
	float:left;
}

/* Be sure to place a .clear element after each set of columns, just to be safe */
.clear { display: block; clear: both; }


/* ------------------------------------------- 
		PHONE
		For clients that support media queries.
		Nothing fancy. 
-------------------------------------------- */
@media only screen and (max-width: 600px) {
	
	a[class="btn"] { display:block!important; margin-bottom:10px!important; background-image:none!important; margin-right:0!important;}

	div[class="column"] { width: auto!important; float:none!important;}
	
	table.social div[class="column"] {
		width:auto!important;
	}

}
</style>

<table class="body-wrap">
	<tr>
		<td></td>
		<td class="container" bgcolor="#FFFFFF">
			<br />
			<p>Your current application status : <b></b></p>
			<% if @visa.first.status == 'Verified' %>				
				<p>Please scroll below to find out your payment information</p>
			<% elsif @visa.first.status == 'Approved' %>
				<p>Congratulations! Your application is approved, please find out the detail below</p>
			<% else %>
				<p><b>Your application is currently under review/process</b></p>
			<% end %>
			<div class="content">
			<table>
				<tr>
					<td>						
						<p></p>						
						<h6><b>Application Ref.</b></h6>
						<p><h3><b><%= @visa.first.ref_id %></b></h3></p>	
						<h6><b>Applicant Detail</b></h6>
						
					<center><table>							
							<tr>
								<td>Application Type</td>
								<td>
									<% if @visa.count > 1 %>
										Group/Family Visa : <%= @visa.count %> Person(s)
									<% else %>
										Individual Visa
									<% end %></td>
							</tr>
							<tr>
								<td>Grantee Detail</td>
								<td><% @visa.each do |row| %>
										<b><%= row.first_name + ' ' + row.last_name %></b>  (<%= row.category_type %>) :  <%= (row.status=='Verified' || row.status == 'Printed' || row.status == 'Paid' || row.status == 'Approved' )? Visafee.where(:id => row.visafee_ref).first.name_of_visa : 'Under Review' %><br />
									<% end %>
								</td>
							</tr>
					</table></center>
					
						<br />
						<br />
						<hr /><br />
						<% if @visa.first.status == 'Verified' %>
						<h6><b>Payment Information</b></h6>
						
						<% tp = 0 
						@visa.each do |row| %>
						 <% tp += Visafee.where(:id => row.visafee_ref).first.fee_of_visa %>
						<% end %>
						
						<h2>$<%= tp %></h2>
						<p style="text-align:justify;">Please make your payment through <b>KEB Bank (외환은행)</b>. Indonesian Embassy in Seoul account <b>650-005012-179</b> proceed with <b>Dollar currency payment (Foreign Currency Deposit Slip / 외화예금전표 )</b>. Currency : <b>USD</b></p>
						<br />
						<p><b>Please rewrite the Reference Number to the Depositor Name section in the payment slip. Example : <a href="">Payment slip</a></b></p>
						<br />
						<br />
						<hr /><br />						
						<% end %>
						<!-- A Real Hero (and a real human being) -->	
						
						<!-- Callout Panel -->
						<p class="callout" style="text-align:justify;">
						 You may visit <a href="http://kbri.seoul.kr">http://kbri.seoul.kr</a> or contact our office for more information about your application
						</p><!-- /Callout Panel -->
						
						<center><h5>Thank you for using Indonesian Embassy electronic system</h5></center>
						
					
					</td>
				</tr>
			</table>
			</div>
									
		</td>
		<td></td>
	</tr>
</table>